spring:
  application:
    name: employee-access-management

  datasource:
    url: jdbc:postgresql://localhost:5432/access_management
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWN1cmVTZWNyZXRLZXlGb3JEZXYxMjM0NTY3ODkw}
  expiration: ${JWT_EXPIRATION:3600000}